### PR TITLE
Fix Minor Issues

### LINKED ISSUE #18: Email Already in Use No Error Handling
CleanShot 2022-12-26 at 14 12 27@2x

### PR DESCRIPTION
**Pull request by juangarciaSD**
- Resolved #18 with adding new function
- Resovled blank screen pop up after log out

### CODE REVIEW

**Comment by filippo-fonseca** [comment]
Thanks so much, @fangskillz!!

**Comment by filippo-fonseca** [comment]
*this has actually already been fixed in another branch!!

**Comment by filippo-fonseca** [comment]
will use the email exist thing though :)

**Comment by juangarciaSD** [comment]
Ready for PR!

**Comment by filippo-fonseca** [comment]
> Ready for PR!

merged!

**Pull request merged**
